spring:
  datasource:
    username: root
    password: stefan
    url: jdbc:mysql://192.168.111.130:33306/ypin_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: ypin-product
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 10001
